coffeedapp/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'coffeedapp.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    (r'', include('core.urls')),
)

core/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
import core.views as coreviews
from django.contrib.auth.decorators import login_required

urlpatterns = patterns('',

    url(r'^$', coreviews.LandingView.as_view()),
    url(r'location/$', coreviews.LocationListView.as_view()),
    url(r'search/$', coreviews.SearchListView.as_view()),
    url(r'location/(?P<pk>\d+)/detail/$', coreviews.LocationDetailView.as_view(), name='location_detail'),
    url(r'location/create/$', login_required(coreviews.LocationCreateView.as_view())),
    url(r'location/(?P<pk>\d+)/update/$', login_required(coreviews.LocationUpdateView.as_view()), name='location_update'),
    url(r'location/(?P<pk>\d+)/review/create/$', login_required(coreviews.ReviewCreateView.as_view()), name='review_create'),
    url(r'location/(?P<pk>\d+)/review/update/$', login_required(coreviews.ReviewUpdateView.as_view()), name='review_update'),
    url(r'entrance/$', coreviews.entrance),
)

core/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.db.models import Avg
from geoposition.fields import GeopositionField

import os
import uuid

def upload_to_location(instance, filename):
    blocks = filename.split('.')
    ext = blocks[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    instance.title = blocks[0]
    return os.path.join('uploads/', filename)

RATING_CHOICES = (
    (0, 'None'),
    (1, '*'),
    (2, '**'),
    (3, '***'),
    (4, '****'),
    (5, '*****'),
    )

YESNO_CHOICES = (
    (0, 'No'),
    (1, 'Yes')
    )

PLURAL_CHOICES = (
    (0, 'None'),
    (1, 'Minimal'),
    (2, 'Some'),
    (3, 'Ample')
    )

WIFI_CHOICES = (
    (0, 'None'),
    (1, 'Spotty'),
    (2, 'Strong')
    )

COFFEE_CHOICES = (
    (0, 'None'),
    (1, 'Truck Stop'),
    (2, 'Good'),
    (3, 'Really Good'),
    (4, 'Great'),
    )

def upload_to_location(instance, filename):
    blocks = filename.split('.')
    ext = blocks[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    instance.title = blocks[0]
    return os.path.join('uploads/', filename)

# Create your models here.

class Location(models.Model):
    title = models.CharField(max_length=300)
    description = models.TextField(null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    position = GeopositionField(null=True, blank=True)
    hours = models.TextField(null=True, blank=True)
    image_file = models.ImageField(upload_to=upload_to_location, null=True, blank=True)
    wifi = models.IntegerField(choices=WIFI_CHOICES, null=True, blank=True)
    seating = models.IntegerField(choices=PLURAL_CHOICES, null=True, blank=True)
    outlets = models.IntegerField(choices=PLURAL_CHOICES, null=True, blank=True)
    bathrooms = models.IntegerField(choices=YESNO_CHOICES, null=True, blank=True)
    coffee = models.IntegerField(choices=COFFEE_CHOICES, null=True, blank=True)
    alcohol = models.IntegerField(choices=YESNO_CHOICES, null=True, blank=True)
    outdoor = models.IntegerField(choices=YESNO_CHOICES, null=True, blank=True)
    food = models.IntegerField(choices=YESNO_CHOICES, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(viewname="location_detail", args=[self.id])

    def get_average_rating(self):
        average = self.review_set.all().aggregate(Avg('rating'))['rating__avg']
        if average == None:
            return average
        else:
            return int(average)

    def get_reviews(self):
        return self.review_set.all()


class Review(models.Model):
    location = models.ForeignKey(Location)
    user = models.ForeignKey(User)
    description = models.TextField(null=True, blank=True)
    rating = models.IntegerField(choices=RATING_CHOICES, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

core/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
import core.models as coremodels
from sitegate.decorators import redirect_signedin, sitegate_view


# Create your views here.

class LandingView(TemplateView):
	template_name = 'base/index.html'


class LocationListView(ListView):
	model = coremodels.Location
	template_name = 'location/list.html'
	paginate_by = 5

class SearchListView(LocationListView):

	def get_queryset(self):
		incoming_query_string = self.request.GET.get('query', '')
		return coremodels.Location.objects.filter(title__icontains=incoming_query_string)

class LocationDetailView(DetailView):
	model = coremodels.Location
	template_name = 'location/detail.html'
	context_object_name = 'location'

	def get_context_data(self, **kwargs):
		context = super(LocationDetailView, self).get_context_data(**kwargs)
		location = coremodels.Location.objects.get(id=self.kwargs['pk'])
		if self.request.user.is_authenticated():
			user_reviews = coremodels.Review.objects.filter(location=location, user=self.request.user)
			if user_reviews.count() > 0:
				context['user_review'] = user_reviews[0]
			else:
				context['user_review'] = None

		return context

class LocationCreateView(CreateView):
	model = coremodels.Location
	template_name = 'base/form.html'


class LocationUpdateView(UpdateView):
	model = coremodels.Location
	template_name = 'base/form.html'


class ReviewCreateView(CreateView):
	model = coremodels.Review
	template_name = 'base/form.html'
	fields =['description', 'rating']

	def form_valid(self, form):
		form.instance.user = self.request.user
		form.instance.location = coremodels.Location.objects.get(id=self.kwargs['pk'])
		return super(ReviewCreateView, self).form_valid(form)

	def get_success_url(self):
		return self.object.location.get_absolute_url()



class ReviewUpdateView(UpdateView):
	model = coremodels.Review
	template_name = 'base/form.html'
	fields =['description', 'rating']

	def get_object(self):
		return coremodels.Review.objects.get(location__id=self.kwargs['pk'], user=self.request.user)

	def get_success_url(self):
		return self.object.location.get_absolute_url()

@sitegate_view(widget_attrs={'class': 'form-control', 'placeholder': lambda f: f.label}, template='form_bootstrap3')  # This also prevents logged in users from accessing our sign in/sign up page.
def entrance(request):
    return render(request, 'base/entrance.html', {'title': 'Sign in & Sign up'})

templates/base/entrance.html
{% extends "base/theme.html" %}
{% load sitegate %}
{% block main_content %}

<section id="services">
    <div class="container">
        <div class="row ">
            <div class="col-lg-6 text-center">
                <div class="my_signin_block">
                    <h2 class="section-heading"><a href="{{ location.get_absolute_url }}">Sign In</a></h2>
                    <h3 class="section-subheading text-muted">Welcome back!</h3>
                    {% sitegate_signin_form %}
                </div>
            </div>
            <br>
            <div class="col-lg-6 text-center">
                <div class="my_signup_block">
                    <h2 class="section-heading"><a href="{{ location.get_absolute_url }}">Join Get Coffeed</a></h2>
                    <h3 class="section-subheading text-muted">Find your favorite office away from home.</h3>
                    {% sitegate_signup_form %}
                </div>
            </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/base/form.html
{% extends "base/theme.html" %}
{% load widget_tweaks %}
{% block main_content %}
    <div class="header-buffer">
    </div>
    <section id="services">
        <div class="container">
<div class="row">
  {% if form %}
  <div class="col-md-12">
   <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}{{ form.media }}
    {% for field in form %}
    <div class="form-group warning">
     <label for="exampleInputFile">{{ field.label }}</label>
     {{ field|add_class:"form-control"}}
     {% if field.help_text %}<p class="help-block">{{ field.help_text }}</p>{% endif %}
   </div>
   {% if field.errors %}
   {% for error in field.errors %}
   <div class="alert alert-danger" id="error_{{ field.name }}">{{ error|escape }}</div>
   {% endfor %}
   {% endif %}

   {% endfor %}
   <input type="submit" class="btn btn-success" role="button" value="{{ verb|default:"Submit" }}" />
 </form>
</div>
{% endif %}
</div>
</div>
</section>
{% endblock %}

templates/base/rating.html
<div class="coffeed-rating">
{% if rating == 1 %}
<i class="fa fa-heart"></i><i class="fa fa-heart-o"></i><i class="fa fa-heart-o"></i><i class="fa fa-heart-o"></i><i class="fa fa-heart-o"></i>
{% elif rating == 2 %}
<i class="fa fa-heart"></i><i class="fa fa-heart"></i><i class="fa fa-heart-o"></i><i class="fa fa-heart-o"></i><i class="fa fa-heart-o"></i>
{% elif rating == 3 %}
<i class="fa fa-heart"></i><i class="fa fa-heart"></i><i class="fa fa-heart"></i><i class="fa fa-heart-o"></i><i class="fa fa-heart-o"></i>
{% elif rating == 4 %}
<i class="fa fa-heart"></i><i class="fa fa-heart"></i><i class="fa fa-heart"></i><i class="fa fa-heart"></i><i class="fa fa-heart-o"></i>
{% elif rating == 5 %}
<i class="fa fa-heart"></i><i class="fa fa-heart"></i><i class="fa fa-heart"></i><i class="fa fa-heart"></i><i class="fa fa-heart"></i>
{% else %}
<i class="fa fa-heart-o"></i><i class="fa fa-heart-o"></i><i class="fa fa-heart-o"></i><i class="fa fa-heart-o"></i><i class="fa fa-heart-o"></i>
{% endif %}
</div>

templates/base/review.html
<div class="row">
    <div class="col-md-8">
        <h2>{{ review.user.get_full_name }} <a class="subheading"> | {{ review.created_at | date }}</a></h2>
    </div>
    <div class="col-md-4 text-right">
        <h2>{% include 'base/rating.html' with rating=review.rating %}</h2>
    </div>
 
</div>
<p>{{ review.description }}</p>

templates/base/theme.html
{% extends "base/index.html" %}

{% block navigation %}
    <li>
        <a class="page-scroll" href="/location">Find a Coffee Shop</a>
    </li>
    {% if user.is_authenticated %}
    <li>
        <a class="page-scroll" href="/location/create/">Add a Location</a>
    </li> 
    {% else %}
    <li>
        <a class="page-scroll" href="/entrance/">Log In</a>
    </li> 
    {% endif %}     
{% endblock %}

{% block search %}
<form action="/search/" class="navbar-form navbar-right" method="get">
	<div class="form-group">
		<input type="text" placeholder="Search" class="form-control" name="query"></input>
	</div>
</form>
{% endblock %}

{% block main_content %}
Stuff goes here
{% endblock %}

templates/location/detail.html
{% extends "base/theme.html" %}
{% block scripts %}
<script src="http://maps.google.com/maps/api/js?sensor=true"></script>
<script src="{{ STATIC_URL }}theme/js/gmaps.js"></script>
<script src="{{ STATIC_URL }}theme/js/maps.js"></script>
{% endblock %}
{% block main_content %}
<div class="data-layer">
    <ul>
        <li class="location-data" data-latitude="{{ location.position.latitude }}" data-longitude="{{ location.position.longitude }}">{{ location.title }}</li>
    </ul>
</div>
<div class="header-buffer">
</div>
<!-- Services Section -->
<section id="services">
    <div class="container">
        <div class="" >
            <div id="details">
<div class="col-md-12">
<div class="row">
                            <div class="col-md-8">
                            <h2>{{ location.title }}</h2>
                            </div>
                            <div class="col-md-4 text-right">
                            <h2>{% include 'base/rating.html' with rating=location.get_average_rating %}</h2>
                            </div>


                            </div>

                <div class="col-md-8">
                    <div class="row">
                            {% if location.image_file %}
                        <div class="col-md-12" >
                        
                        <img src="{{ location.image_file.url }}" class="img-responsive img-centered full-width" alt="">

                      </div>
                      {% endif %}
                  
                  <div class="row">
                    <div class="col-md-12" >{% include 'location/specifics.html' with location=location %}
                    </div>
                </div>
        <div class="row">
            <div class="col-md-12">
                <p class="">{{ location.description}}</p>
                        <div class="">
                            {% if user.is_authenticated %}
                            <a type="button" href="{% url 'location_update' pk=location.id %}" class="btn btn-default">Edit</a>
                            {% endif %}

                        </div>
            </div>
        </div>
        </div>
            </div>
            
            <div class="col-md-4 panel">
                <div class="wide-map short-map" id="map"></div>
                <div class="col-md-3"></div>
                <div class="col-md-6 text-center">
                <br>
                    {% if location.address %}<p>{{ location.address }}</p>{% endif %}
                    {% if location.phone %}<p>{{ location.phone }}</p>{% endif %}
                    {% if location.website %}<p><a href="{{ location.website }}">{{ location.website }}</a></p>{% endif %}
                </div>
                <div class="col-md-3"></div>
            </div>
            </div>
        </div>

    </div>
    <div id="reviews">
    <div class="col-md-12">
    <hr>
                {% if user.is_authenticated %}
                        {% if user_review %}
                        <a type="button" href="{% url 'review_update' pk=location.id %}" class="btn btn-default pull-right">Update Review</a>
                        {% else %}
                        <a type="button" href="{% url 'review_create' pk=location.id %}" class="btn btn-default pull-right">Add Your Review</a>
                        {% endif %}
                {% endif %}
    </div>

        <div>
            <div class="col-md-8">
                {% if user_review %}
                {% with user_review as review %}
                <div>
                    {% include 'base/review.html' %}
                </div>


                {% endwith %}
                {% endif %}
                {% for review in reviews %}
                {% include 'location/review.html' %}
                <hr>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
</section>
{% endblock %}

templates/location/list.html
{% extends "base/theme.html" %}
{% load bootstrap_pagination %}
{% block main_content %}
<div class="data-layer">
	<ul>
	{% for location in object_list %}
		<li class="location-data" data-latitude="{{ location.position.latitude }}" data-longitude="{{ location.position.longitude }}" data-id="{{ location.id }}">{{ location.title }}</li>
	{% endfor %}
	</ul>
</div>
<div id="map" class="wide-map"></div>
<div class="row main-content">
	<div class="col-md-2"></div>
	<div class="col-md-8">
	{% for location in object_list %}
		<div class='row'>
		<div class="col-md-8">
			<h3><a href="{{ location.get_absolute_url }}">{{ location.title }}</a></h3>
		</div>
		<div class="col-md-4 text-right">
			<h3>{% include 'base/rating.html' with rating=location.get_average_rating %}</h3>
		</div>
		<div class="col-md-8">
		{% if location.address %}<p><b>Location: </b>{{ location.address }}</b></p>{% endif %}
		{% if location.hours %}<p>{{ location.hours }}</p>{% endif %}
		{% if location.image_file %}
			<img class="img-responsive" src="{{ location.image_file.url }}"></img>
		{% endif %}
		{% include 'location/specifics.html' with location=location %}
		<p>{{ location.description }}</p>
	</div>
	</div>
	{% endfor %}
	</div>
	<div class="col-md-2"></div>
</div>
{% endblock %}

{% block pagination %}
	{% bootstrap_paginate page_obj range=10 show_prev_next="false" show_first_last="true" %}
{% endblock %}

templates/location/specifics.html
 
<div class="row">
<div class="col-md-4">
 
<p><b>WIFI: </b>{% if location.wifi %}{{ location.get_wifi_display }}{% else %}----{% endif %}</p>
<p><b>Seating: </b>{% if location.seating %}{{ location.get_seating_display }}{% else %}----{% endif %}</p>
<p><b>Outlets: </b>{% if location.outlets %}{{ location.get_outlets_display }}{% else %}----{% endif %}</p>
<p><b>Bathrooms: </b>{% if location.bathroom %}{{ location.get_bathrooms_display }}{% else %}----{% endif %}</p>
</div>
<div class="col-md-4">
<p><b>Coffee: </b>{% if location.coffee %}{{ location.get_coffee_display }}{% else %}----{% endif %}</p>
<p><b>Seating: </b>{% if location.alcohol %}{{ location.get_alcohol_display }}{% else %}----{% endif %}</p>
<p><b>Outdoor Seating: </b>{% if location.outdoor %}{{ location.get_outdoor_display }}{% else %}----{% endif %}</p>
<p><b>Food: </b>{% if location.food %}{{ location.get_food_display }}{% else %}----{% endif %}</p>
</div>
</div>